### ISSUE TITLE
Doens't run on Windows 8

### ISSUE THREAD

**Issue by cachitas** [cachitas/uar#1]
Clicking `Extract Images` does nothing. Looks like it blocked in the first file to extract.

The following error is silently raised:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Common Files\Python\3.4\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\Unzip Alignment Results\pkgs\uar.py", line 120, in extract_images
    zfiledata = io.BytesIO(zfile.read(name))
MemoryError
```

Maybe the installed version of Python with `Pynsist` is 32-bit. We need 64-bit to read such big files in memory.

**Comment by cachitas** [comment]
Fixed with bca20b80f3f1c13d9f9a7328bd38cdd717183c51.

Nothing was done regarding the memory error. We will assume the machine has enough RAM to extract the files.
